# A sample pipeline implementation
pipelines:
  pull-requests:
    "**":
      # Other steps in the pipeline
      # 👇 Adds Chromatic as a step in the pipeline
      - step:
          image: node:16
          name: "Publish to Chromatic"
          # Other pipeline configuration
          script:
            - npm install
              # 👇 Runs Chromatic with the flag to prevent pipeline failure
            - npm run chromatic
