# A sample pipeline implementation
pipelines:
  pull-requests:
    "**":
      # Other steps in the pipeline
      # 👇 Adds Chromatic as a step in the pipeline
      - step:
          image: node:16
          name: "Publish to Chromatic"
          # Other pipeline configuration
          script:
            - npm install
              # 👇 Runs Chromatic with the flag to prevent pipeline failure
            - npm run chromatic
      - step:
          image: node:16
          name: "Publish to percy"
          # Other pipeline configuration
          script:
            - npm install
              # 👇 Runs Chromatic with the flag to prevent pipeline failure
            - npm run percy
          environment:
            - PERCY_TOKEN=$PERCY_TOKEN
      - step:
          image: node:16
          name: "Publish to applitools"
          # Other pipeline configuration
          script:
            - npm install
              # 👇 Runs Chromatic with the flag to prevent pipeline failure
            - npm run applitools
          environment:
            - APPLITOOLS_API_KEY=$APPLITOOLS_API_KEY
