# A sample pipeline implementation
pipelines:
  pull-requests:
    "**":
      # Other steps in the pipeline
      # 👇 Adds Chromatic as a step in the pipeline
      - step:
          image: node:16
          name: "Publish to Chromatic"
          # Other pipeline configuration
          script:
            - npm install
              # 👇 Runs Chromatic with the flag to prevent pipeline failure
            - npm run chromatic
      # - step:
      #     image: node:16
      #     name: "Publish to percy"
      #     # Other pipeline configuration
      #     script:
      #       - npm install
      #       - npm run build-storybook -- --quiet
      #       - apt-get install -y libnss3 libxss1 libasound2
      #         # 👇 Runs Chromatic with the flag to prevent pipeline failure
      #       - npm run percy
      #     environment:
      #       - PERCY_TOKEN=$PERCY_TOKEN
      - step:
          image: node:16
          name: "Publish to applitools"
          # Other pipeline configuration
          script:
            - npm install
              # 👇 Runs Chromatic with the flag to prevent pipeline failure
            - apt-get update && apt-get install -yq libgconf-2-4
            - apt-get update && apt-get install -y libnss3 && \
              libxss1 && \
              libasound2 && \
              # Dont worry about cleaning up files left after installation.
            - npm run applitools
          environment:
            - APPLITOOLS_API_KEY=$APPLITOOLS_API_KEY
