# A sample pipeline implementation
pipelines:
  pull-requests:
    "**":
      # Other steps in the pipeline
      # 👇 Adds Chromatic as a step in the pipeline
      # - step:
      #     image: node:16
      #     name: "Publish to Chromatic"
      #     # Other pipeline configuration
      #     script:
      #       - npm install
      #         # 👇 Runs Chromatic with the flag to prevent pipeline failure
      #       - npm run chromatic
      # - step:
      #     image: node:16
      #     name: "Publish to percy"
      #     # Other pipeline configuration
      #     script:
      #       - npm install
      #       - npm run build-storybook -- --quiet
      #         - apt-get update && apt-get install -y libnss3 && \
      #         libxss1 && \
      #         libasound2 && \
      #         # 👇 Runs Chromatic with the flag to prevent pipeline failure
      #       - npm run percy
      #     environment:
      #       - PERCY_TOKEN=$PERCY_TOKEN
      - step:
          image: node:16
          name: "Publish to applitools"
          # Other pipeline configuration
          script:
            # 👇 Runs Chromatic with the flag to prevent pipeline failure
            - groupadd -r pwuser && useradd -r -g pwuser -G audio,video pwuser
            - mkdir -p /home/pwuser/Downloads
            - mkdir -p /home/pwuser/tests
            - chown -R pwuser:pwuser /home/pwuser
            - su - pwuser
            - apt-get update && apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
            - npm install
            - npm run build-storybook -- --quiet
            - npm run applitools
          environment:
            - APPLITOOLS_API_KEY=$APPLITOOLS_API_KEY
